### PR TITLE
Suggest alternative yaml highlighter

### PR DESCRIPTION
**Pull request by kremso**
I added a simple note about slow YAML syntax highlighting per #32.

### CODE REVIEW

**Comment by gravyboat** [comment]
Thanks for adding this! I'm sure one of the devs will be around to merge it shortly.

**Comment by jfindlay** [comment]
bam!

**Comment by jfindlay** [comment]
Thanks, guys.

**Comment by gravyboat** [comment]
Thanks @jfindlay!

**Pull request merged**
